### ISSUE TITLE
Workflow step: Auto-commit images

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/nautilus-librarian#31]
We are migrating the logic on the [Gold Drawing Processing workflow](https://github.com/Nautilus-Cyberneering/chinese-ideographs/blob/main/.github/workflows/gold-drawings-processing.yml) from the [library](https://github.com/Nautilus-Cyberneering/chinese-ideographs) to the librarian (this repo).

The last step in the workflow is "Auto-commit of the images":

```
- name: Auto-commit added or modified images
  id: auto-commit
  uses: ./.github/actions/auto-commit-images
  env:
    AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
    AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
  with:
    repository: "${{ github.repository }}"
    repo_dir: "${{ github.workspace }}"
    repo_token: "${{ secrets.GITHUB_TOKEN }}"
    branch: "${{ github.head_ref }}"
```

In its simplest case (adding a new Gold image), this action extracts the list of added Base images using `git diff` and creates a commit to add each image to the PR branch (one commit per image). When the workflow is triggered it checks if there are new Gold images. In case there are some of them, it automatically generates the Base image (lower resolution version of the Gold image). This step detects the newly generate Base image using git and adds it to dvc storage and git repo.

There are at least two things we want to change from the [previous implementation](https://github.com/Nautilus-Cyberneering/chinese-ideographs/tree/main/.github/actions/auto-commit-images):

1. We do not need to use `git diff` to get the list of the newly generated Base images. We already have the list of new Gold images and there should be at least one corresponding Base image for each of them.
2. We used GitHub API to create and sign the commits. We found that working with the same branch locally (local branch in the runner) and remotely (via the GitHub API) leads to a lot of git conflicts, so we decided to use the [GitPython](https://github.com/gitpython-developers/GitPython) package. [Here](https://github.com/josecelano/pygithub/blob/main/docs/how_to_sign_commits_using_the_gitpython_package.md) you can find how to use it, including how to sign the commits.
