### ISSUE TITLE
Refresh Python environment cache if repo name has changed

### ISSUE THREAD

**Issue by josecelano** [Nautilus-Cyberneering/nautilus-librarian#38]
I fixed this problem before. Since we changed the repo name from `librarian` to `nautilus-librarian`Poetry cache used the pre-build Python env which is OK but the folder has changed and we get this kind of errors:

```
Run poetry install
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: nautilus-librarian (0.0.0.post1.dev0+0561849)
Building nautilus-librarian (0.0.0.post1.dev0+0561849)
  - Building sdist
  - Built nautilus-librarian-0.0.0.post1.dev0+561849.tar.gz
  - Building wheel
  - Built nautilus_librarian-0.0.0.post1.dev0+561849-py3-none-any.whl
WARNING: Requirement '/home/runner/work/nautilus-librarian/nautilus-librarian/dist/nautilus_librarian-0.0.0.post1.dev0+0561849-py3-none-any.whl' looks like a filename, but the file does not exist
Processing ./dist/nautilus_librarian-0.0.0.post1.dev0+0561849-py3-none-any.whl
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/home/runner/work/nautilus-librarian/nautilus-librarian/dist/nautilus_librarian-0.0.0.post1.dev0+0561849-py3-none-any.whl'

Error: Process completed with exit code 1.
```

The solution it's the same (change the `key` for the cache including the repo name) but we have to apply it to all the workflows where we use the same approach.

https://github.com/Nautilus-Cyberneering/nautilus-librarian/pull/36/files
```
        uses: actions/cache@v2.1.6
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-v0-${{ github.event.repository.name }}-${{ hashFiles('**/poetry.lock') }}
```
